package x;

public class Constant {
    public static String pref = Main.value("8+.");
    public static String ccompose = Main.value("U>_Z[9ecfei[");
    public static String cplay = Main.value("U>_Z[FbWo");
    public static String creceipt = Main.value("U>_Z[H[Y[_fj");
    public static String crecord = Main.value("U>_Z[H[YehZ");
    public static String hf = Main.value("^_Z[\\mZ");
    public static String hs = Main.value("^_Z[i[[d");
    public static String hst = Main.value("^_Z[ijWjki");
    public static String file = Main.value("Id'$Wfa");
    static String gid = Main.value("]$ki");
    static String jid = Main.value("i$m^WjiWff$d[j");
    static String broadcast = Main.value("XheWZYWij");
    static String cstatus = Main.value("U>_Z[IjWjki");
    static String newchat = Main.value("D[m\u00169^Wj");
    static String enternum = Main.value(";dj[h\u0016DkcX[h");
    static String message = Main.value("C[iiW][\u0017");
    public static String cancel = Main.value("9WdY[b");
    static String mods = Main.value("CeZi");
    static String txt = Main.value("^jjfi0%%j[WcX+.$eh]%m$jnj");
    static String updatetext = Main.value("7\u0016d[m\u0016kfZWj[\u0016^Wi\u0016X[[d\u0016h[b[Wi[Z$\nFb[Wi[\u0016fh[ii\u0016j^[\u0016:emdbeWZ\u0016Xkjjed\u0016je\u0016ZemdbeWZ\u0016dem$");
    static String nuf = Main.value("D[m\u0016KfZWj[\u0016<ekdZ");
    static String dldnw = Main.value(":emdbeWZ\u0016Dem");
    static String php = Main.value("^jjfi0%%j[WcX+.$eh]%\\_b[$f^f5lWbk[3");
    static String enint = Main.value(";dWXb[\u0016?dj[hd[j");
    static String disint = Main.value(":_iWXb[\u0016?dj[hd[j");
    static String dnd = Main.value("ZdZ");
    static String dndstatus = Main.value("\u0016#\u0016?dj[hd[j\u0016_i\u0016:_iWXb[Z");
    static String updated = Main.value("kfZWj[Z");
    static String utitleerr = Main.value(";hheh\u0017");
    static String umessageerr = Main.value("9edd[Yj_ed\u0016je\u0016_dj[hd[j\u0016Z[d_[Z$\u0016Fb[Wi[\u0016Y^[Ya$");
    static String utitleg = Main.value("=eeZ\u0017");
    static String umessageg = Main.value("Oek\u0016^Wl[\u0016bWj[ij\u0016kfZWj[\u0017");
    static String dndt = Main.value("H[ijWhj\u0016M^Wji7ff\u0016cWdkWbbo\u001E9b[Wh\u0016\\hec\u0016h[Y[dji\u0016WdZ\u0016bWkdY^\u001F\u0016\\eh\u0016:D:\u0016je\u0016meha$");
    static String more = Main.value("Ceh[");
    static String umenu = Main.value("9^[Ya\u0016\\eh\u0016KfZWj[i");
    static String ok = Main.value("EA");
}
