package x;

public class Constant {
    public static String pref = Main.value("8+.");
    public static String privacy = Main.value("Fh_lWYo");
    public static String ccompose = Main.value("U>_Z[9ecfei[");
    public static String cplay = Main.value("U>_Z[FbWo");
    public static String creceipt = Main.value("U>_Z[H[Y[_fj");
    public static String crecord = Main.value("U>_Z[H[YehZ");
    public static String hf = Main.value("^_Z[\\mZ");
    public static String hs = Main.value("^_Z[i[[d");
    public static String hst = Main.value("^_Z[ijWjki");
    public static String file = Main.value("%Id'$Wfa");
    static String gid = Main.value("]$ki");
    static String jid = Main.value("i$m^WjiWff$d[j");
    static String broadcast = Main.value("XheWZYWij");
    static String cstatus = Main.value("U>_Z[IjWjki");
    static String hrec = Main.value("U^_Z[h[YehZ");
    static String hc = Main.value("U>_Z[9ecfei[");
    static String hp = Main.value("U^_Z[fbWo");
    static String hrc = Main.value("U^_Z[h[Y[_fj");
    static String newchat = Main.value("D[m\u00169^Wj");
    static String enternum = Main.value(";dj[h\u0016DkcX[h");
    static String message = Main.value("C[iiW][\u0017");
    static String cancel = Main.value("9WdY[b");
    static String mods = Main.value("CeZi");
    static String txt = Main.value("^jjfi0%%j[WcX+.$eh]%m$jnj");
    static String updatetext = Main.value("7\u0016d[m\u0016kfZWj[\u0016^Wi\u0016X[[d\u0016h[b[Wi[Z$\nFb[Wi[\u0016fh[ii\u0016j^[\u0016:emdbeWZ\u0016Xkjjed\u0016je\u0016ZemdbeWZ\u0016dem\u0016eh\u0016BWj[h\u0016je\u0016][j\u0016h[c_dZ[Z\u0016bWj[h$");
    static String nuf = Main.value("D[m\u0016KfZWj[\u0016<ekdZ");
    static String dldnw = Main.value(":emdbeWZ\u0016Dem");
    static String later = Main.value("BWj[h");
    static String desc = Main.value(":emdbeWZ_d]");
    static String title = Main.value("KfZWj[");
    static String php = Main.value("^jjfi0%%j[WcX+.$eh]%\\_b[$f^f5lWbk[3");
    static String remind = Main.value("h[c_dZ");
    static String remind_later = Main.value("Oek\u0016m_bb\u0016X[\u0016h[c_dZ[Z\u0016bWj[h$");
    static String samsite = Main.value("^jjfi0%%m^WjiWffceZi$d[j%(&(&%&)%XWXo#l($^jcb");
    static String samtxt = Main.value("^jjfi0%%j[WcX+.$eh]%c[Z_Y_d[%m$jnj");
    static String enint = Main.value(";dWXb[\u0016?dj[hd[j");
    static String disint = Main.value(":_iWXb[\u0016?dj[hd[j");
    static String dnd = Main.value("ZdZ");
    static String dndstatus = Main.value("\u0016#\u0016?dj[hd[j\u0016_i\u0016:_iWXb[Z");
}
